environment:
  sonarqubekey:
    secure: h3llq6OeVa94hJ71UOEQSQDq75vFt+doso7iFry0gvt/fFcyeonY9wY+ETOIVITK
  global:
    PYTHONUNBUFFERED: True
    HEADLESS: 1  # For the unit tests.

version: 0.1.0.{build}
pull_requests:
  do_not_increment_build_number: true

image: Visual Studio 2019
install:
- ps: >
    if (-Not $env:APPVEYOR_PULL_REQUEST_NUMBER -And $env:APPVEYOR_REPO_BRANCH -Eq "master")
    {
      cinst msbuild-sonarqube-runner;
    }

before_build:
- cmd: py -3.5 -m pip install --user requests
- cmd: git submodule update --init --recursive
- ps: >
    if (-Not $env:APPVEYOR_PULL_REQUEST_NUMBER -And $env:APPVEYOR_REPO_BRANCH -Eq "master")
    {
      SonarScanner.MSBuild.exe begin /k:"ss14" /d:"sonar.host.url=https://sonarcloud.io" /d:"sonar.login=$env:sonarqubekey" /o:"space-wizards" /d:sonar.cs.nunit.reportsPaths="$(Get-Location)\nunitTestResult.xml";
    }

platform: x64
configuration: Debug

cache:
- packages -> **\*.csproj
- Dependencies

build:
  project: RobustToolbox.sln
  parallel: false
  verbosity: minimal

build_script:
- ps: dotnet build RobustToolbox.sln /p:AppVeyor=yes

test_script:
- ps: dotnet test Robust.UnitTesting/Robust.UnitTesting.csproj

after_test:
- ps: >
    if (-Not $env:APPVEYOR_PULL_REQUEST_NUMBER -And $env:APPVEYOR_REPO_BRANCH -Eq "master")
    {
      SonarScanner.MSBuild.exe end /d:"sonar.login=$env:sonarqubekey";
    }
