language: csharp

dist: trusty
sudo: false

os:
- linux
- osx

addons:
  apt:
    packages:
    - nunit-console

before_install:
  - if [ $TRAVIS_OS_NAME = osx ]; then brew update && brew install python3; fi

before_script:
- "python3 ./Resources/buildResourcePack.py --resources-dir ./Resources --out ./Resources/ResourcePack.zip --no-atlas --no-animations --to-stderr"
- "nuget restore SpaceStation14.sln"

script:
- "xbuild /p:Configuration=Release /p:HEADLESS=1 SpaceStation14.sln"
- "nunit-console SS14.UnitTesting/bin/Release/SS14.UnitTesting.dll"

