language: csharp

dist: bionic
sudo: false
mono: none
# dotnet: 3.1.100 # Travis is shitting itself right now and it can't locate .NET Core packages.

os:
- linux
#- osx

addons:
  apt:
    #sources:
    #- deadsnakes

    packages:
    - python3
    - python3-pip

cache:
  directories:
  - packages/
  - Dependencies/
  - Robust.Client.Godot/.mono/assemblies/

install:
- curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --version 3.1.100

#before_install:
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew update && brew upgrade python; fi

before_script:
- "python3.6 -m pip install --user requests"
- "python3.6 RUN_THIS.py --no-prompt"

script:
- "Tools/run_travis.sh"

