language: csharp

# Beta distribution for running SonarQube
dist: trusty

os:
- linux
- osx

addons:
  apt:
    packages:
    - nunit-console
  # Linter and quality checker
  sonarqube:
    organization: "space-wizards"
    token:
      secure: "fQs1fUYpbK1mf/vlEimYmJdGSV0iKhd7w6rp/B8RuiZJxKIdntaJhXdqKcgixq71lf1IlXVasKYNCNiuy73KonJIDK47FhlglQCLoDQLIKvTr3Is7gTZQAuYqUzMJ7rPk4TP+/aUUhxQWtWKgJPgdkekr9ai5FWv94xDv8d57Yw="
 
env:
- HEADLESS=1

before_script:
- "curl http://84.195.252.227/static/ResourcePack.zip -o Resources/ResourcePack.zip"
- "nuget restore SpaceStation14.sln"

script:
- "xbuild /p:Configuration=Release SpaceStation14.sln"
- "nunit-console SS14.UnitTesting/bin/Release/SS14.UnitTesting.dll"
- sonar-scanner
