
[log]
path = "logs"
format = "log_%(date)s-%(time)s.txt"
level = 1
enabled = false

[net]
tickrate = 60
port = 1212
bindto = "::,0.0.0.0"

# The status server is the TCP side, used by the launcher to determine engine version, etc.
[status]
enabled = true
bind = "*:1212"

# This is the address of the SS14 server as the launcher uses it.
# This is only needed if you're proxying the status HTTP server.
# connectaddress = "udp://localhost:1212"

[game]
hostname = "MyServer"
# map = "maps/saltern.yml"
maxplayers = 64
type = 1
welcomemsg = "Welcome to the server!"

[console]
# If this is true, people connecting from this machine (loopback)
# will automatically be elevated to full admin privileges.
# This literally works by checking if address == 127.0.0.1 || address == ::1
loginlocal = true

[build]
# *Absolutely all of these can be supplied using a "build.json" file*
# For further information, see https://github.com/space-wizards/space-station-14/blob/master/Tools/gen_build_info.py
# The main reason you'd want to supply any of these manually is for a custom fork and if you have no tools.

# Almost never optional, but also don't have a good value for this.
# See https://github.com/space-wizards/RobustToolbox/tags for version values, remove the 'v'.
# The value listed here is almost certainly wrong - it is ONLY a demonstration of format.
# engine_version = "0.7.6"

# This one is optional, the launcher will delete other ZIPs of the same fork to save space.
# fork_id = "abacusstation"

# Automatically set if self-hosting client zip, but otherwise use this when updating client build.
# There is no required format, any change counts as a new version.
# version = "Example1"

# This is where the launcher will download the client ZIP from.
# If this isn't supplied, the server will check for a file called "Content.Client.zip",
#  and will host it on the status server.
# download_url = "http://example.com/compass.zip"

# Build hash - this is a *capitalized* SHA256 hash of the client ZIP.
# build = "E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855"

[auth]
# Authentication (accounts):
# 0 = Optional, 1 = Required, 2 = Disabled
# Presumably do require authentication on any public server.
# mode = 0

# If true, even if authentication is required, localhost is still allowed to login directly regardless.
# allowlocal = true

# You should probably never EVER need to touch this, but if you need a custom auth server,
# (the auth server being the one which manages Space Station 14 accounts), you change it here.
# server = https://central.spacestation14.io/auth/

