name: Benchmarks
on:
  schedule:
    - cron: '0 5 * * *'
  push:
    tags:
      - 'v*'

env:
  ROBUST_BENCHMARKS_ENABLE_SQL: 1
  ROBUST_BENCHMARKS_SQL_ADDRESS: ${{ secrets.BENCHMARKS_WRITE_ADDRESS }}
  ROBUST_BENCHMARKS_SQL_PORT: ${{ secrets.BENCHMARKS_WRITE_PORT }}
  ROBUST_BENCHMARKS_SQL_USER: ${{ secrets.BENCHMARKS_WRITE_USER }}
  ROBUST_BENCHMARKS_SQL_PASSWORD: ${{ secrets.BENCHMARKS_WRITE_PASSWORD }}
  ROBUST_BENCHMARKS_SQL_DATABASE: benchmarks

jobs:
  benchmark:
    name: Run Benchmarks
    runs-on: ubuntu-latest
    steps:
    - name: Run script on centcomm
      uses: appleboy/ssh-action@master
      with:
        host: centcomm.spacestation14.io
        username: robust-benchmark-runner
        key: ${{ secrets.CENTCOMM_ROBUST_BENCHMARK_RUNNER_KEY }}
        script: |
          wget https://github.com/space-wizards/RobustToolbox/blob/master/Tools/run_benchmarks.py
          python3 run_benchmarks.py ${{ secrets.BENCHMARKS_WRITE_ADDRESS }} ${{ secrets.BENCHMARKS_WRITE_PORT }} ${{ secrets.BENCHMARKS_WRITE_USER }} ${{ secrets.BENCHMARKS_WRITE_PASSWORD }} $GITHUB_SHA
          rm run_benchmarks.py
